version: "3.98"
services:
  ai-server:
    container_name: ai_server
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./:/usr/app
    environment:
      - CONFIG_PATH=/usr/app/ai_server/config/server.toml
    working_dir: /usr/app
    # Running in unbuffered mode => using for debugging when using with docker
    command: >
      sh -c "python3 -u app.py" 
    # command: >
    #   sh -c "python3 app.py" 
    # restart: always
    ports:
      - "5005:5005"
      - "50052:50052"
    networks:
      - backend 

networks:
  backend:
    external: true
    name: backend
    driver: bridge
