FROM python:3.8

WORKDIR /usr/app

RUN apt-get update \
    && apt-get install -y --no-install-recommends ffmpeg

RUN pip install --timeout 1000 torch>=1.7.0,!=1.12.0 torchvision>=0.8.1,!=0.13.0

COPY requirements.txt .

RUN pip install --timeout 1000 -r requirements.txt

COPY . .

EXPOSE 5005

ENV TZ="Asia/Ho_Chi_Minh"

CMD [ "python3", "app.py" ]
