# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import camera_stream_info_pb2 as camera__stream__info__pb2


class CameraStreamInfoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCameraStream = channel.unary_unary(
                '/CameraStreamInfoService/CreateCameraStream',
                request_serializer=camera__stream__info__pb2.CreateCameraStreamRequest.SerializeToString,
                response_deserializer=camera__stream__info__pb2.CreateCameraStreamResponse.FromString,
                )
        self.UpdateCameraStreamById = channel.unary_unary(
                '/CameraStreamInfoService/UpdateCameraStreamById',
                request_serializer=camera__stream__info__pb2.UpdateCameraStreamByIdRequest.SerializeToString,
                response_deserializer=camera__stream__info__pb2.UpdateCameraStreamByIdResponse.FromString,
                )
        self.DeleteCameraStreamById = channel.unary_unary(
                '/CameraStreamInfoService/DeleteCameraStreamById',
                request_serializer=camera__stream__info__pb2.DeleteCameraStreamByIdRequest.SerializeToString,
                response_deserializer=camera__stream__info__pb2.DeleteCameraStreamByIdResponse.FromString,
                )


class CameraStreamInfoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCameraStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCameraStreamById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCameraStreamById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CameraStreamInfoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCameraStream': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCameraStream,
                    request_deserializer=camera__stream__info__pb2.CreateCameraStreamRequest.FromString,
                    response_serializer=camera__stream__info__pb2.CreateCameraStreamResponse.SerializeToString,
            ),
            'UpdateCameraStreamById': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCameraStreamById,
                    request_deserializer=camera__stream__info__pb2.UpdateCameraStreamByIdRequest.FromString,
                    response_serializer=camera__stream__info__pb2.UpdateCameraStreamByIdResponse.SerializeToString,
            ),
            'DeleteCameraStreamById': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCameraStreamById,
                    request_deserializer=camera__stream__info__pb2.DeleteCameraStreamByIdRequest.FromString,
                    response_serializer=camera__stream__info__pb2.DeleteCameraStreamByIdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CameraStreamInfoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CameraStreamInfoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCameraStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CameraStreamInfoService/CreateCameraStream',
            camera__stream__info__pb2.CreateCameraStreamRequest.SerializeToString,
            camera__stream__info__pb2.CreateCameraStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCameraStreamById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CameraStreamInfoService/UpdateCameraStreamById',
            camera__stream__info__pb2.UpdateCameraStreamByIdRequest.SerializeToString,
            camera__stream__info__pb2.UpdateCameraStreamByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCameraStreamById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CameraStreamInfoService/DeleteCameraStreamById',
            camera__stream__info__pb2.DeleteCameraStreamByIdRequest.SerializeToString,
            camera__stream__info__pb2.DeleteCameraStreamByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
