[server]
    [server.http]
        host = "localhost"
        port = "3001"
        protocol = "http"


[rabbitmq]
    host = "localhost"
    username = "guest"
    password = "guest"
    port = "5672"
    virtual_host = "/"
    protocol = "amqp"


    [[rabbitmq.exchanges]]

        name = "event_processing"
        [[rabbitmq.exchanges.queues]]
            name = "event_created_with_media"
            binding_keys = ["event.media.*"]

        [[rabbitmq.exchanges.queues]]
            name = "event_verified"
            binding_keys = ["event.verified.iot.*", "event.verified.camera.*"]


[event]
    [event.iot]
        door_open = { key = "door_open" }
        movement = { key = "movement" }

    [event.camera]
        crowd_gathering = { key = "crowd_gathering" }
        line_crossing = { key = "line_crossing" }


