[server]
    [server.http]
        host = "localhost"
        port = "5000"
        protocol = "http"


[rabbitmq]
    host = "localhost"
    username = "guest"
    password = "guest"
    port = "5672"
    virtual_host = "/"
    protocol = "amqp"


    [[rabbitmq.exchanges]]

        [[rabbitmq.exchanges.event_processing]]
            name = "event_processing"
            [[rabbitmq.exchanges.event_processing.queues]]
                name = "event_created_with_media"
                binding_keys = ["event.media.*"]

            [[rabbitmq.exchanges.event_processing.queues]]
                name = "event_verified"
                binding_keys = ["event.verified.iot.*", "event.verified.camera.*"]

        [[rabbitmq.exchanges.stream_processing]]
            name = "stream_processsing"
            


[event]
    [event.iot]
        door_open = { key = "door_open" }
        movement = { key = "movement" }

    [event.camera]
        crowd_gathering = { key = "crowd_gathering" }
        line_crossing = { key = "line_crossing" }


[static]
    [static.path]
        general_image = "/static/general/image"
        detection_image = "/static/detection/image"
        detection_video = "/static/detection/video"



